package redact

import (
	"strings"
	"testing"
)

func TestEntropyCatchesShapelessSecrets(t *testing.T) {
	// The credentials no vendor prefix will ever cover: rotated database
	// passwords, internal service tokens, anything generated by `openssl
	// rand -base64`.
	cases := []string{
		`SESSION_KEY="Xk9pQ2mZ7vR4tY8wN3bL6cJ1hF5dS0aG"`,
		"internal_service_auth: hT7kP2xW9qN4mB8vC3zL6yR1jD5sA0fG",
		`{"apiSecret": "9mK4nP7qR2wX5tY8zA3bC6dF1gH0jL4v"}`,
	}
	r := mustNew(t, Options{})
	for _, in := range cases {
		out := r.Redact(in)
		if !strings.Contains(out, "[REDACTED:high-entropy:") {
			t.Errorf("entropy fallback missed:\n in: %s\nout: %s", in, out)
		}
	}
}

func TestEntropyIgnoresTheHashesThatFillRealRepos(t *testing.T) {
	// This is the case the whole design of entropy.go is bent around: hex
	// tops out at 4 bits/char, below the 4.5 floor, so lockfiles and git
	// objects are structurally immune rather than accidentally spared.
	cases := []string{
		`"integrity": "sha512-1234567890abcdef1234567890abcdef1234567890abcdef"`,
		`"resolved": "0123456789abcdef0123456789abcdef01234567"`,
		`commit: "9f2c8ab4e5d6c7b8a9f0e1d2c3b4a5f6e7d8c9b0"`,
		`"id": "550e8400-e29b-41d4-a716-446655440000"`,
		`checksum = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"`,
	}
	r := mustNew(t, Options{})
	for _, in := range cases {
		if out := r.Redact(in); out != in {
			t.Errorf("hex digest was redacted (this would mangle every lockfile):\n in: %s\nout: %s", in, out)
		}
	}
}

func TestEntropyRequiresValuePosition(t *testing.T) {
	// A random-looking run floating in prose or code is not a credential
	// claim. Requiring assignment/quote context is constraint #1.
	free := "the build produced Xk9pQ2mZ7vR4tY8wN3bL6cJ1hF5dS0aG as output"
	r := mustNew(t, Options{})
	if out := r.Redact(free); out != free {
		t.Errorf("free-floating token was redacted: %s", out)
	}
}

func TestEntropyRespectsLengthBounds(t *testing.T) {
	r := mustNew(t, Options{})
	short := `k="Xk9pQ2mZ7vR4tY8"` // 15 chars — under minEntropyLen
	if out := r.Redact(short); out != short {
		t.Errorf("sub-minimum run was redacted: %s", out)
	}
	huge := `k="` + strings.Repeat("Xk9pQ2mZ7v", 60) + `"` // 600 chars — over max
	if strings.Contains(r.Redact(huge), "high-entropy") {
		t.Error("oversized blob was redacted; blobs are not credentials")
	}
}

func TestEntropyCanBeDisabled(t *testing.T) {
	// The format rules are the high-confidence half; an operator whose repo
	// trips the fallback should be able to keep the rest.
	r := mustNew(t, Options{NoEntropy: true})

	// A key whose NAME declares it secret is still caught by
	// secret-assignment — that layer is untouched.
	named := `API_TOKEN="Xk9pQ2mZ7vR4tY8wN3bL6cJ1hF5dS0aG"`
	if out := r.Redact(named); !strings.Contains(out, "[REDACTED:secret-assignment:") {
		t.Errorf("format rules should still cover a secret-named key: %s", out)
	}

	// And this is the cost of switching the fallback off, asserted rather
	// than left implicit: SESSION_KEY is a real credential, but "key" on
	// its own is not a secrecy claim (map key, sort key, cache key), so no
	// format rule declares it and only entropy would have caught it.
	shapeless := `SESSION_KEY="Xk9pQ2mZ7vR4tY8wN3bL6cJ1hF5dS0aG"`
	if out := r.Redact(shapeless); out != shapeless {
		t.Errorf("NoEntropy did not disable the fallback: %s", out)
	}
	if out := mustNew(t, Options{}).Redact(shapeless); out == shapeless {
		t.Errorf("with entropy on, the same value should be caught: %s", out)
	}
}

func TestEntropyDisabledViaRuleID(t *testing.T) {
	r := mustNew(t, Options{Disable: []string{"high-entropy"}})
	in := `internal_auth: hT7kP2xW9qN4mB8vC3zL6yR1jD5sA0fG`
	if out := r.Redact(in); strings.Contains(out, "high-entropy") {
		t.Errorf("disabling by rule id did not work: %s", out)
	}
}

func TestShannonMatchesKnownDistributions(t *testing.T) {
	// Pins the reasoning in entropy.go's threshold comment: if these move,
	// entropyFloor is no longer sitting in the gap it was chosen for.
	cases := []struct {
		name     string
		s        string
		min, max float64
	}{
		{"hex digest", "0123456789abcdef0123456789abcdef01234567", 3.0, 4.0},
		{"random base64", "Xk9pQ2mZ7vR4tY8wN3bL6cJ1hF5dS0aG", 4.5, 6.0},
		{"repeated char", strings.Repeat("a", 40), 0, 0.001},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			h := shannon(tc.s)
			if h < tc.min || h > tc.max {
				t.Errorf("shannon = %.2f, want within [%.2f, %.2f]", h, tc.min, tc.max)
			}
		})
	}
}

func TestLooksRandomRejectsIdentifiers(t *testing.T) {
	// Composition constraint #3: things that clear the entropy floor for
	// the wrong reason.
	for _, s := range []string{
		"averylongfunctionnamewithoutdigits",     // no digits
		"1234567890123456789012345",              // no letters
		"path/to/some/nested/directory/file123",  // multiple slashes
		"query=value&other=thing123456789012345", // interior '='
	} {
		if looksRandom(s) {
			t.Errorf("looksRandom(%q) = true, want false", s)
		}
	}
}
